[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dspring.profiles.active=dev -Xmx300m -XX:+ExitOnOutOfMemoryError -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
