sonar.projectKey=kavach-ai_backend
sonar.projectName=KAVACH AI Backend
sonar.organization=YOUR_SONAR_ORG

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/generated/**,**/*Application.java

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.qualitygate.wait=true
