-- DEVICES ------------------------------------------------------------------
-- Drop old devices table if it exists (from V1__init.sql)
DROP TABLE IF EXISTS devices CASCADE;

CREATE TABLE devices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID REFERENCES tenants(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL DEFAULT 'Unnamed Device',
    type            VARCHAR(50) NOT NULL DEFAULT 'DESKTOP'
                      CHECK (type IN ('DESKTOP','LAPTOP','TABLET','MOBILE')),
    status          VARCHAR(50) NOT NULL DEFAULT 'OFFLINE'
                      CHECK (status IN ('ONLINE','OFFLINE','PAUSED','FOCUS_MODE')),
    os_version      VARCHAR(100),
    agent_version   VARCHAR(20),
    hostname        VARCHAR(255),
    last_seen       TIMESTAMP,
    assigned_to     VARCHAR(255),
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW()
);

-- DEVICE LINK CODES --------------------------------------------------------
-- Codes are generated by the desktop agent and used once to link the device
CREATE TABLE IF NOT EXISTS device_link_codes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(10) UNIQUE NOT NULL,
    tenant_id   UUID,                          -- null until linked
    device_id   UUID REFERENCES devices(id) ON DELETE CASCADE,
    used        BOOLEAN DEFAULT FALSE,
    expires_at  TIMESTAMP NOT NULL,
    created_at  TIMESTAMP DEFAULT NOW()
);

-- INDEXES ------------------------------------------------------------------
-- devices table was just (re)created, so IF NOT EXISTS is safe here too
CREATE INDEX IF NOT EXISTS idx_devices_tenant     ON devices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_devices_status     ON devices(status);
CREATE INDEX IF NOT EXISTS idx_link_code          ON device_link_codes(code);
CREATE INDEX IF NOT EXISTS idx_link_code_used     ON device_link_codes(used, expires_at);

-- SEED DEMO DEVICES --------------------------------------------------------
INSERT INTO devices (id, tenant_id, name, type, status, os_version, agent_version, hostname, assigned_to, last_seen)
VALUES
  ('d1111111-1111-1111-1111-111111111111',
   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
   'Lab PC - Row A1', 'DESKTOP', 'ONLINE',
   'Windows 11 Pro', '1.2.4', 'SUNRISE-PC-01', 'Rahul Sharma',
   NOW()),

  ('d2222222-2222-2222-2222-222222222222',
   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
   'Lab PC - Row A2', 'DESKTOP', 'FOCUS_MODE',
   'Windows 10 Pro', '1.2.4', 'SUNRISE-PC-02', 'Priya Verma',
   NOW()),

  ('d3333333-3333-3333-3333-333333333333',
   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
   'Lab PC - Row B1', 'LAPTOP', 'OFFLINE',
   'Windows 11 Home', '1.2.3', 'SUNRISE-LAP-01', 'Arjun Singh',
   NOW() - INTERVAL '1 hour'),

  ('d4444444-4444-4444-4444-444444444444',
   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
   'Lab PC - Row B2', 'DESKTOP', 'PAUSED',
   'Windows 11 Pro', '1.2.4', 'SUNRISE-PC-04', 'Sneha Patel',
   NOW() - INTERVAL '30 minutes'),

  ('d5555555-5555-5555-5555-555555555555',
   'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
   'Home Laptop - Rohan', 'LAPTOP', 'ONLINE',
   'Windows 11 Home', '1.2.4', 'ROHAN-HOME-LAP', 'Rohan Gupta',
   NOW());
