/**
 * AUTO-GENERATED by scripts/write-build-config.cjs — do not edit manually.
 * Generated at: 2026-03-19T13:44:55.363Z
 * Source: API_URL environment variable (never committed)
 */
export const BUILD_API_URL = 'https://kavach-core-production.up.railway.app';
