/**
 * AUTO-GENERATED by scripts/write-build-config.cjs — do not edit manually.
 * Generated at: 2026-03-19T12:54:57.823Z
 * Source: API_URL environment variable (never committed)
 */
export const BUILD_API_URL = 'http://localhost:8080';
